name: export
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  export-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Build PDF
        uses: actions/checkout@v2
        run: |
          npm i -g md-to-pdf
          md-to-pdf ./arindas-resume.md
      - name: Archive PDF
        uses: actions/upload-artifact@v2
        name: arindas-resume.pdf
        path: ./arindas-resume.pdf
