name: export
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - arindas-resume.md

jobs:
  export-to-pdf:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v4

      - name: Install bun js
        uses: oven-sh/setup-bun@v2

      - name: Export to pdf
        run: |
          bun install -g md-to-pdf
          bunx puppeteer browsers install chrome
          md-to-pdf ./arindas-resume.md

      - name: Archive PDF
        uses: actions/upload-artifact@v4
        with:
          name: arindas-resume
          path: ./arindas-resume.pdf
