name: export
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - arindas-resume.md

jobs:
  export-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v2
      - name: Export to pdf
        run: |
          npm i -g md-to-pdf
          md-to-pdf ./arindas-resume.md
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: arindas-resume
          path: ./arindas-resume.pdf
